### ISSUE TITLE
hxt-regex-xmlschema fails to build with GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [UweSchmidt/hxt#89]
```
src/Text/Regex/XMLSchema/Generic/Matching.hs:247:27: error:
    Parse error in pattern: !n
    |
247 |     token' re' fcs' (uns, ! n) inp
    |                           ^^^
```

See https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#whitespace-sensitive-and- for background.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision to prohibit unbuildable configuration:
https://hackage.haskell.org/package/hxt-regex-xmlschema-9.2.0.3/revisions/
